### ISSUE TITLE
Bug with routes in production

### ISSUE THREAD

**Issue by giojavi04** [tavo1987/mini-framework#1]
Routes functionallity work correctly in local, but in production not recognize any route only /. Give error type MethodNotAllowed

**Comment by tavo1987** [comment]
I've proved the routes on production and  working correctly

if these are in a directory try this `$app->get('/directory/thanks', [ThanksController::class, 'index']);` and uses an updated version of php, you could force the version with the .htaccess file, for example `AddHandler application/x-httpd-php56 .php`
